- name: Upload build to staging path
  uses: appleboy/scp-action@v0.1.4
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    source: 'index.html'
    target: '/home/ubuntu/deploy-temp/'

- name: Move to /var/www/html with sudo
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      sudo mkdir -p /var/www/html
      sudo mkdir -p /home/ubuntu/deploy-temp
      sudo rm -rf /var/www/html/*
      sudo mv /home/ubuntu/deploy-temp/* /var/www/html/
