name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List files in workspace
        run: ls -la
      - name: Create target directory on server
        run: ssh -i ${{ secrets.KEY }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "mkdir -p /var/www/html/"
      - name: SCP files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: .
          target: /var/www/html/
          debug: true
      - name: Check tar file
        run: ls -l /tmp/*.tar.gz || echo "No tar file found"
